version: '3.2'
services:
  frontend:
    image: node:16.4.2
    working_dir: /usr/local/frontend
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/local/frontend
      - frontend_node_modules:/usr/local/frontend/node_modules

  e2e:
    image: "cypress/included:7.7.0"
    working_dir: /usr/local/e2e
    volumes:
      - ./e2e:/usr/local/e2e
    environment:
      - CYPRESS_baseUrl=http://frontend:3000
    depends_on:
      - frontend

volumes:
  frontend_node_modules:

# env_file:
#   - .env.development.local
# this is the web application we are going to test
#   sentimentalyzer:
# build: ../
# environment:
#   - PORT=8123
# Cypress container